/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cTelaLogView.java
 *
 * Created on Oct 2, 2010, 9:19:15 AM
 */

package gui;

import javax.swing.table.AbstractTableModel;
import main.cRegistros;

/**
 *
 * @author luizfelipe
 */
public class cTelaLogView extends javax.swing.JFrame {

  /** Creates new form cTelaLogView */
  public cTelaLogView(final cRegistros r) {

    initComponents();

    mostraRegistrosDialogo(r);

  }

  private void mostraRegistrosDialogo(final cRegistros r) {
    
    tabela.setModel(new AbstractTableModel() {

      @Override
      public String getColumnName(int col) {
        if(col == 0)
          return "Data";
        return "Registros";
      }

      public int getRowCount() {
        return r.l.size();
      }

      public int getColumnCount() {
        return 2;
      }

      public Object getValueAt(int row, int col) {
        if(col == 0) {
          return r.lst.get(r.l.get(row)).getHora();
        }
        return r.lst.get(r.l.get(row)).getRegistro();
      }

      @Override
      public boolean isCellEditable(int row, int col) {
        return false;
      }

    });

    tabela.getColumnModel().getColumn(0).setPreferredWidth(100);
    tabela.getColumnModel().getColumn(1).setPreferredWidth(400);

    tabela.validate();
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tabela = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    tabela.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Data", "Registro"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tabela.setColumnSelectionAllowed(true);
    tabela.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(tabela);
    tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
    tabela.getColumnModel().getColumn(0).setPreferredWidth(10);
    tabela.getColumnModel().getColumn(1).setPreferredWidth(400);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
    );

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-637)/2, (screenSize.height-296)/2, 637, 296);
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new cTelaLogView().setVisible(true);
//            }
//        });
//    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tabela;
  // End of variables declaration//GEN-END:variables

}
