/*
 * PUC-Rio - Pontificia Universidade Catolica
 * Bacharelado em Sistemas de Informacao
 *
 * INF 1416 - Seguranca da Informacao 2010.1     Turma: 3WA
 * Trabalho P1
 * Professor: Anderson Oliveira da Silva
 *
 * Grupo: Henrique Taunay
 *        Luiz Felipe Machado
 */

/*
 * cTelaLogin.java
 *
 * Created on Sep 23, 2010, 7:26:43 AM
 */
package gui;

import controlador.cControlador;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author luizfelipe
 */
public class cTelaLogin extends javax.swing.JFrame {

  private cControlador controlador;

  /** Creates new form cTela */
  public cTelaLogin(cControlador controlador) {

    initComponents();

    this.controlador = controlador;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    l_login = new javax.swing.JLabel();
    tf_login = new javax.swing.JTextField();
    b_entrar = new javax.swing.JButton();
    b_sair = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Login");
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    l_login.setText("Identificacao do Usuario:");

    tf_login.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_entrarActionPerformed(evt);
      }
    });

    b_entrar.setText("Entrar");
    b_entrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_entrarActionPerformed(evt);
      }
    });

    b_sair.setText("Sair");
    b_sair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_sairActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(l_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(tf_login, javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addComponent(b_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(b_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(13, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(l_login)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tf_login, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(b_entrar)
          .addComponent(b_sair))
        .addContainerGap())
    );

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-257)/2, (screenSize.height-129)/2, 257, 129);
  }// </editor-fold>//GEN-END:initComponents

    private void b_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_entrarActionPerformed

      String login = tf_login.getText();

      if(login.isEmpty()) {
        JOptionPane.showMessageDialog(this.getContentPane(), "Campo de login vazio.");
        return;
      }

      // verifica se usuario esta cadastrado
      if(!controlador.carregaUsuario(login)) {

        // usuario nao esta cadastrado
        controlador.salvaRegistro(2005, login);
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Usuario " + login + " nao esta cadastrado no sistema.");

      } else {
        // usuario esta cadastrado

        // Verifica se o usuario esta bloqueado
        if(controlador.verificaUsuarioBloqueado()) {


          // usuario bloqueado
          controlador.salvaRegistro(2004, login);
          JOptionPane.showMessageDialog(this.getContentPane(),
                                        "Usuario " + login + " esta bloqueado.");
          controlador.deslogaUsuario();

        } else {

          // usuario cadastrado e nao esta bloqueado
          controlador.salvaRegistro(2003, login);
          controlador.mostraTelaLogin(false);
          controlador.salvaRegistro(2002, "");
          controlador.mostraTelaSenhaPessoal(true);
        }
      }

    }//GEN-LAST:event_b_entrarActionPerformed

    private void b_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sairActionPerformed
      controlador.desconectaBanco();
      System.exit(0);
    }//GEN-LAST:event_b_sairActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      controlador.desconectaBanco();
    }//GEN-LAST:event_formWindowClosing
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton b_entrar;
  private javax.swing.JButton b_sair;
  private javax.swing.JLabel l_login;
  private javax.swing.JTextField tf_login;
  // End of variables declaration//GEN-END:variables
}
