/*
 * PUC-Rio - Pontificia Universidade Catolica
 * Bacharelado em Sistemas de Informacao
 *
 * INF 1416 - Seguranca da Informacao 2010.1     Turma: 3WA
 * Trabalho P1
 * Professor: Anderson Oliveira da Silva
 *
 * Grupo: Henrique Taunay
 *        Luiz Felipe Machado
 */

/*
 * cTelaSenhaCartao.java
 *
 * Created on Sep 24, 2010, 5:41:14 PM
 */
package gui;

import controlador.cControlador;
import java.util.Vector;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import main.cCartaoSenhas;

/**
 *
 * @author luizfelipe
 */
public class cTelaSenhaCartao extends javax.swing.JFrame {

  private cControlador controlador = null;
  public static int numTentativas = 0;
  private int numSenhaCartao = -1;

  /** Creates new form cTelaSenhaCartao */
  public cTelaSenhaCartao(cControlador controlador) {

    this.controlador = controlador;

    initComponents();
  }

  public void sorteiaSUV(cCartaoSenhas senhas) {

    tf_senha.setText("");

    Vector vsenhas = this.controlador.retornaSenhasLivres();

    if(vsenhas.isEmpty()) {
      JOptionPane.showMessageDialog(this.getContentPane(), "Usuario nao tem mais senhas unicas.");
      System.exit(1);
    }

    // utiliza como semente o tempo em milisegundos
    Random gerador = new Random(new Date().getTime());

    int gerado = gerador.nextInt(vsenhas.size());
    int result = (Integer) vsenhas.get(gerado);
    numSenhaCartao = result;
    /*if(numSenhaCartao == 0) {
    ++numSenhaCartao;
    }*/
    l_num_senha.setText(Integer.toString(numSenhaCartao));
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    l_num_senha = new javax.swing.JLabel();
    tf_senha = new javax.swing.JTextField();
    b_entrar = new javax.swing.JButton();
    b_sair = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    jLabel1.setText("Insira a senha do cartao numero: ");

    l_num_senha.setFont(new java.awt.Font("Tahoma", 1, 14));
    l_num_senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_num_senha.setText("10");

    tf_senha.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_entrarActionPerformed(evt);
      }
    });

    b_entrar.setText("Entrar");
    b_entrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_entrarActionPerformed(evt);
      }
    });

    b_sair.setText("Sair");
    b_sair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_sairActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(tf_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(l_num_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(b_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
            .addComponent(b_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(l_num_senha))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(b_entrar)
          .addComponent(b_sair))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-247)/2, (screenSize.height-132)/2, 247, 132);
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    controlador.desconectaBanco();
  }//GEN-LAST:event_formWindowClosing

  private void b_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sairActionPerformed
    controlador.mostraTelaSenhaCartao(false);
    controlador.mostraTelaLogin(true);
  }//GEN-LAST:event_b_sairActionPerformed

  private void b_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_entrarActionPerformed

    String senhaDigitada = tf_senha.getText();

    // verifica os caracteres das senhas selecionadas
    if(!controlador.verificaCaracteresSenhaCartao(senhaDigitada)) {
      ++numTentativas;

      if(numTentativas == 1) {
        controlador.salvaRegistro(4004, "");
      } else if(numTentativas == 2) {
        controlador.salvaRegistro(4005, "");
      } else {
        controlador.salvaRegistro(4006, "");
      }


      if(numTentativas >= 3) {

        controlador.salvaRegistro(4007, controlador.getUsuarioCorrente().getLogin());

        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Usuario "
                                      + controlador.getUsuarioCorrente().getLogin()
                                      + " foi bloqueado por 2 minutos!");
        controlador.bloqueiaUsuario();

        return;
      } else {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "A senha precisa ter 4 caracteres (letras maiusculas de A a Z e numeros de 0 a 9).\n"
                                      + "Tentativas: " + numTentativas + "/3.");
      }

      return;
    }

    // verifica se a senha eh valida
    if(!controlador.verificaSenhaCartao(senhaDigitada, numSenhaCartao - 1)) {
      ++numTentativas;

      if(numTentativas == 1) {
        controlador.salvaRegistro(4004, "");
      } else if(numTentativas == 2) {
        controlador.salvaRegistro(4005, "");
      } else {
        controlador.salvaRegistro(4006, "");
      }

      JOptionPane.showMessageDialog(this.getContentPane(), "A senha errada!\n"
                                                           + "Tentativas: " + numTentativas + "/3.");

      if(numTentativas >= 3) {

        controlador.salvaRegistro(4007, controlador.getUsuarioCorrente().getLogin());

        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Usuario "
                                      + controlador.getUsuarioCorrente().getLogin()
                                      + " foi bloqueado por 2 minutos!");
        controlador.bloqueiaUsuario();

        return;
      }

      return;
    }

    // senha valida
    controlador.salvaRegistro(4003, "");
    controlador.marcaSenhaUtilizada(numSenhaCartao);
    controlador.mostraTelaSenhaCartao(false);
    controlador.salvaRegistro(4002, "");
    controlador.mostraTelaPrincipal(true);
  }//GEN-LAST:event_b_entrarActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton b_entrar;
  private javax.swing.JButton b_sair;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel l_num_senha;
  private javax.swing.JTextField tf_senha;
  // End of variables declaration//GEN-END:variables
}
