/*
 * PUC-Rio - Pontificia Universidade Catolica
 * Bacharelado em Sistemas de Informacao
 *
 * INF 1416 - Seguranca da Informacao 2010.1     Turma: 3WA
 * Trabalho P1
 * Professor: Anderson Oliveira da Silva
 *
 * Grupo: Henrique Taunay
 *        Luiz Felipe Machado
 */

/*
 * cTelaSenhaPessoal.java
 *
 * Created on Sep 23, 2010, 8:22:05 AM
 */
package gui;

import controlador.cControlador;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import main.eFonemas;

/**
 *
 * @author luizfelipe
 */
public class cTelaSenhaPessoal extends javax.swing.JFrame {

  private cControlador controlador = null;
  /*
   * lista com os 9 botoes
   */
  private Vector<JButton> lstBotao = null;

  /*
   * lista com os fonemas que foram selecionados
   * essa lista nao pode passar de 3 (quantidade maxima para as senhas pessoais)
   * essa lista tambem contem a os outros fonemas do botao selecionado
   */
  private Vector<String> lstFonemasSelecionados = null;

  /*
   * quantidade de tentativas realizadas pelo usuario
   */
  static public int numTentativas = 0;

  /** Creates new form cTelaSenha */
  public cTelaSenhaPessoal(cControlador controlador) {

    // inicia componentes
    initComponents();

    lstFonemasSelecionados = new Vector<String>();
    lstBotao = new Vector<JButton>();

    lstBotao.add(bt_1);
    lstBotao.add(bt_2);
    lstBotao.add(bt_3);
    lstBotao.add(bt_4);
    lstBotao.add(bt_5);
    lstBotao.add(bt_6);

    this.controlador = controlador;
  }

  public void limpa() {
    lstFonemasSelecionados.clear();
    pf_senha.setText("");
  }

  /*
   * Essa funcao sorteia e preenche os botoes com os fonemas (eFonemas).
   */
  public void sorteiaFonemaBotao() {

    // Coloca os fonemas em uma lista encadeada apenas para utilizar o Collections.shuffle
    List<String> lst_fonemas = new LinkedList<String>();
    for(eFonemas f : eFonemas.values()) {
      lst_fonemas.add(f.name());
    }

    // utiliza como semente o tempo em milisegundos
    Random gerador = new Random(new Date().getTime());
    // embaralha os fonemas utilizando o gerador aleatorio
    Collections.shuffle(lst_fonemas, gerador);

    // preeche os botoes com os fonemas embaralhados
    String botao = "";
    for(JButton b : lstBotao) {
      botao = lst_fonemas.remove(0);
      botao += " " + lst_fonemas.remove(0);
      botao += " " + lst_fonemas.remove(0);
      botao += " " + lst_fonemas.remove(0);
      b.setText(botao);
    }

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    p_senha = new javax.swing.JPanel();
    bt_2 = new javax.swing.JButton();
    bt_3 = new javax.swing.JButton();
    bt_1 = new javax.swing.JButton();
    bt_4 = new javax.swing.JButton();
    bt_5 = new javax.swing.JButton();
    bt_6 = new javax.swing.JButton();
    pf_senha = new javax.swing.JPasswordField();
    b_entrar = new javax.swing.JButton();
    b_sair = new javax.swing.JButton();
    b_limpar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Senha");
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    p_senha.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    bt_2.setFocusPainted(false);
    bt_2.setFocusable(false);
    bt_2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_letraActionPerformed(evt);
      }
    });

    bt_3.setFocusPainted(false);
    bt_3.setFocusable(false);
    bt_3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_letraActionPerformed(evt);
      }
    });

    bt_1.setFocusPainted(false);
    bt_1.setFocusable(false);
    bt_1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_letraActionPerformed(evt);
      }
    });

    bt_4.setFocusPainted(false);
    bt_4.setFocusable(false);
    bt_4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_letraActionPerformed(evt);
      }
    });

    bt_5.setFocusPainted(false);
    bt_5.setFocusable(false);
    bt_5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_letraActionPerformed(evt);
      }
    });

    bt_6.setFocusPainted(false);
    bt_6.setFocusable(false);
    bt_6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_letraActionPerformed(evt);
      }
    });

    pf_senha.setEditable(false);

    javax.swing.GroupLayout p_senhaLayout = new javax.swing.GroupLayout(p_senha);
    p_senha.setLayout(p_senhaLayout);
    p_senhaLayout.setHorizontalGroup(
      p_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_senhaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(p_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(pf_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
          .addGroup(p_senhaLayout.createSequentialGroup()
            .addComponent(bt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(bt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(p_senhaLayout.createSequentialGroup()
            .addComponent(bt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(bt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    p_senhaLayout.setVerticalGroup(
      p_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_senhaLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(pf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(bt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(bt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(bt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(bt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(44, 44, 44))
    );

    b_entrar.setText("Entrar");
    b_entrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_entrarActionPerformed(evt);
      }
    });

    b_sair.setText("Sair");
    b_sair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_sairActionPerformed(evt);
      }
    });

    b_limpar.setText("Limpar");
    b_limpar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_limparActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(p_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(b_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(b_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(b_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(p_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(b_entrar)
          .addComponent(b_sair)
          .addComponent(b_limpar))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-372)/2, (screenSize.height-289)/2, 372, 289);
  }// </editor-fold>//GEN-END:initComponents

    private void b_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sairActionPerformed

      // TODO (luizfelipe) verificar se Ã© preciso apagar o numero de tentativas
      controlador.salvaRegistro(3002, "");
      controlador.mostraTelaSenhaPessoal(false);
      controlador.mostraTelaLogin(true);

    }//GEN-LAST:event_b_sairActionPerformed

    private void b_letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_letraActionPerformed

      String s = ((JButton) evt.getSource()).getText();
      String split[] = s.split(" ");

      // verifica se foi apertado mais de 3 vezes
      if(lstFonemasSelecionados.size() + 4 <= 12) {


        lstFonemasSelecionados.add(split[0]); // armazena fonema
        lstFonemasSelecionados.add(split[1]); // armazena fonema
        lstFonemasSelecionados.add(split[2]); // armazena fonema
        lstFonemasSelecionados.add(split[3]); // armazena fonema

        // coloca alguma coisa apenas para parecer que inseriu algo
        pf_senha.setText(pf_senha.getText() + split[0]);

        sorteiaFonemaBotao();
      } else {
        // limpa selecionados
        limpa();

        // nao pode ter mais de 3 fonemas
        ++numTentativas;

        controlador.salvaRegistro(3004, "");

        if(numTentativas == 1) {
          controlador.salvaRegistro(3005, "");
        } else if(numTentativas == 2) {
          controlador.salvaRegistro(3006, "");
        } else {
          controlador.salvaRegistro(3007, "");
        }

        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "A senha pessoal nao pode ter mais do que 3 fonemas.\n"
                                      + "Tentativas: " + numTentativas + "/3.");

        if(numTentativas >= 3) {

          controlador.salvaRegistro(3008, controlador.getUsuarioCorrente().getLogin());
          JOptionPane.showMessageDialog(this.getContentPane(),
                                        "Usuario "
                                        + controlador.getUsuarioCorrente().getLogin()
                                        + " foi bloqueado por 2 minutos!");
          controlador.bloqueiaUsuario();

          return;
        }


      }
    }//GEN-LAST:event_b_letraActionPerformed

    private void b_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limparActionPerformed

      limpa();

      sorteiaFonemaBotao();

    }//GEN-LAST:event_b_limparActionPerformed

    private void b_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_entrarActionPerformed

      if(lstFonemasSelecionados.size() == 12 && controlador.verificaSenhaPessoal(lstFonemasSelecionados)) {
        numTentativas = 0;
        controlador.salvaRegistro(3003, "");
        controlador.salvaRegistro(3002, "");
        controlador.mostraTelaSenhaPessoal(false);
        controlador.mostraTelaSenhaCartao(true);
      } else {

        ++numTentativas;
        controlador.salvaRegistro(3004, "");

        if(numTentativas == 1) {
          controlador.salvaRegistro(3005, "");
        } else if(numTentativas == 2) {
          controlador.salvaRegistro(3006, "");
        } else {
          controlador.salvaRegistro(3007, "");
        }

        if(numTentativas >= 3) {

          controlador.salvaRegistro(3008, controlador.getUsuarioCorrente().getLogin());
          JOptionPane.showMessageDialog(this.getContentPane(),
                                        "Usuario "
                                        + controlador.getUsuarioCorrente().getLogin()
                                        + " foi bloqueado por 2 minutos!");
          pf_senha.setText("");
          controlador.bloqueiaUsuario();
          return;
        } else {
          JOptionPane.showMessageDialog(this.getContentPane(),
                                        "Senha invalida.\n"
                                        + "Tentativas: " + numTentativas + "/3.");
        }
      }

      limpa();
    }//GEN-LAST:event_b_entrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      controlador.desconectaBanco();
    }//GEN-LAST:event_formWindowClosing
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton b_entrar;
  private javax.swing.JButton b_limpar;
  private javax.swing.JButton b_sair;
  private javax.swing.JButton bt_1;
  private javax.swing.JButton bt_2;
  private javax.swing.JButton bt_3;
  private javax.swing.JButton bt_4;
  private javax.swing.JButton bt_5;
  private javax.swing.JButton bt_6;
  private javax.swing.JPanel p_senha;
  private javax.swing.JPasswordField pf_senha;
  // End of variables declaration//GEN-END:variables
}
