/*
 * PUC-Rio - Pontificia Universidade Catolica
 * Bacharelado em Sistemas de Informacao
 *
 * INF 1416 - Seguranca da Informacao 2010.1     Turma: 3WA
 * Trabalho P1
 * Professor: Anderson Oliveira da Silva
 *
 * Grupo: Henrique Taunay
 *        Luiz Felipe Machado
 */

/*
 * cTelaPrincipal.java
 *
 * Created on Sep 25, 2010, 2:04:42 PM
 */
package gui;

import controlador.cControlador;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import main.eGrupo;

/**
 *
 * @author luizfelipe
 */
public class cTelaPrincipal extends javax.swing.JFrame {

  private cControlador controlador = null;
  private Vector<JLabel> lstLabelsConsulta = null;

  /** Creates new form cTelaPrincipal */
  public cTelaPrincipal(cControlador controlador) {

    initComponents();

    lstLabelsConsulta = new Vector<JLabel>();
    lstLabelsConsulta.add(l_senha1);
    lstLabelsConsulta.add(l_senha2);
    lstLabelsConsulta.add(l_senha3);
    lstLabelsConsulta.add(l_senha4);
    lstLabelsConsulta.add(l_senha5);
    lstLabelsConsulta.add(l_senha6);
    lstLabelsConsulta.add(l_senha7);
    lstLabelsConsulta.add(l_senha8);
    lstLabelsConsulta.add(l_senha9);
    lstLabelsConsulta.add(l_senha10);

    this.controlador = controlador;

    p_telaPrincipal.setBorder(BorderFactory.createEmptyBorder(10, 10, 0, 0));
    p_telaPrincipal.setLayout(new BoxLayout(p_telaPrincipal, BoxLayout.Y_AXIS));
  }

  public void preencheCabecalho(String nome, String login, String grupo) {
    l_login.setText(login);
    l_grupo.setText(grupo);
    ta_descricao.setText(nome);

    if(grupo.compareTo(eGrupo.Administrador.name()) == 0) {
      b_cadastrarUsuario.setEnabled(true);
    } else {
      b_cadastrarUsuario.setEnabled(false);
    }
  }

  public void preencheConsulta(Vector<String> lst) {

    int i = 0;
    for(JLabel l : lstLabelsConsulta) {
      if(i < lst.size()) {
        l.setText(lst.get(i));
      } else {
        l.setText("");
      }
      ++i;
    }

  }

  public void preencheTotalSUV(String quantidade) {
    this.preencheConsulta(controlador.getUsuarioCorrente().getCartaoSenhas().getLstSenhaHex());
    l_totalSUV.setText(quantidade);
  }

  public void preencheTotalUsuarios(String quantidade) {
    l_totalUsuarios.setText(quantidade);
  }

  public void preecheCadastraSenhaPessoal(String senha) {
    pf_CadastraSenhaPessoal.setText(senha);
  }

  public void preecheCadastraSenhaPessoalConfirma(String senha) {
    pf_CadastraSenhaPessoalConfirma.setText(senha);
  }

  public void mostraTelaPrincipal() {
    p_telaPrincipal.removeAll();

    p_telaPrincipal.add(p_cabecalho);
    p_telaPrincipal.add(p_totalSUV);
    p_telaPrincipal.add(p_menuPrincipal);

    p_telaPrincipal.validate();
    p_telaPrincipal.repaint();
  }

  private void mostraTelaCadastra() {
    controlador.salvaRegistro(6001, controlador.getUsuarioCorrente().getLogin());
    p_telaPrincipal.remove(p_menuPrincipal);
    p_telaPrincipal.remove(p_totalSUV);

    p_telaPrincipal.add(p_totalUsuarios);
    p_telaPrincipal.add(p_cadastra);

    p_telaPrincipal.validate();
    p_telaPrincipal.repaint();
  }

  private void mostraTelaAltera() {
    controlador.salvaRegistro(7001, controlador.getUsuarioCorrente().getLogin());
    p_telaPrincipal.remove(p_menuPrincipal);
    p_telaPrincipal.add(p_alterar);

    p_telaPrincipal.validate();
    p_telaPrincipal.repaint();
  }

  private void mostraTelaConsulta() {
    controlador.salvaRegistro(8001, controlador.getUsuarioCorrente().getLogin());
    p_telaPrincipal.remove(p_menuPrincipal);
    p_telaPrincipal.add(p_consulta);

    p_telaPrincipal.validate();
    p_telaPrincipal.repaint();
  }

  private void mostraTelaSaida() {
    controlador.salvaRegistro(9001, controlador.getUsuarioCorrente().getLogin());
    
    p_telaPrincipal.remove(p_menuPrincipal);
    p_telaPrincipal.add(p_sair);

    p_telaPrincipal.validate();
    p_telaPrincipal.repaint();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    p_totalUsuarios = new javax.swing.JPanel();
    label = new javax.swing.JLabel();
    l_totalUsuarios = new javax.swing.JLabel();
    p_consulta = new javax.swing.JPanel();
    jLabel11 = new javax.swing.JLabel();
    l_senha1 = new javax.swing.JLabel();
    l_senha2 = new javax.swing.JLabel();
    l_senha3 = new javax.swing.JLabel();
    l_senha4 = new javax.swing.JLabel();
    l_senha5 = new javax.swing.JLabel();
    l_senha6 = new javax.swing.JLabel();
    l_senha7 = new javax.swing.JLabel();
    l_senha8 = new javax.swing.JLabel();
    l_senha9 = new javax.swing.JLabel();
    l_senha10 = new javax.swing.JLabel();
    b_voltarConsulta = new javax.swing.JButton();
    p_sair = new javax.swing.JPanel();
    l_msgSaida = new javax.swing.JLabel();
    b_Sair = new javax.swing.JButton();
    b_voltar = new javax.swing.JButton();
    p_alterar = new javax.swing.JPanel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    cb_quantidadeSenhasCartaoAltera = new javax.swing.JComboBox();
    b_alterar = new javax.swing.JButton();
    b_alteraVoltar = new javax.swing.JButton();
    pf_alteraSenhaPessoal = new javax.swing.JPasswordField();
    pf_alteraSenhaPessoalConfirma = new javax.swing.JPasswordField();
    b_alteraSenhaPessoal = new javax.swing.JButton();
    b_alteraSenhaPessoalConfirma = new javax.swing.JButton();
    p_cadastra = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    tf_nome = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    tf_login = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    cb_grupo = new javax.swing.JComboBox();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    cb_quantidadeSenhasCartao = new javax.swing.JComboBox();
    b_cadastrar = new javax.swing.JButton();
    b_voltarCadastra = new javax.swing.JButton();
    b_limpar = new javax.swing.JButton();
    pf_CadastraSenhaPessoal = new javax.swing.JPasswordField();
    pf_CadastraSenhaPessoalConfirma = new javax.swing.JPasswordField();
    b_CadastraSenhaPessoal = new javax.swing.JButton();
    b_CadastraSenhaPessoalConfirma = new javax.swing.JButton();
    p_cabecalho = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    l_grupo = new javax.swing.JLabel();
    l_login = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    ta_descricao = new javax.swing.JTextArea();
    p_totalSUV = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    l_totalSUV = new javax.swing.JLabel();
    p_menuPrincipal = new javax.swing.JPanel();
    b_cadastrarUsuario = new javax.swing.JButton();
    b_AlterarUsuario = new javax.swing.JButton();
    b_consultarUsusario = new javax.swing.JButton();
    b_sairSistema = new javax.swing.JButton();
    p_telaPrincipal = new javax.swing.JPanel();

    p_totalUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

    label.setText("Total de usuarios no sistema:");

    l_totalUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14));
    l_totalUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_totalUsuarios.setText("jLabel11");

    javax.swing.GroupLayout p_totalUsuariosLayout = new javax.swing.GroupLayout(p_totalUsuarios);
    p_totalUsuarios.setLayout(p_totalUsuariosLayout);
    p_totalUsuariosLayout.setHorizontalGroup(
      p_totalUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_totalUsuariosLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(label)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(l_totalUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        .addContainerGap())
    );
    p_totalUsuariosLayout.setVerticalGroup(
      p_totalUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_totalUsuariosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(p_totalUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(label)
          .addComponent(l_totalUsuarios))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    p_consulta.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar  "));

    jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLabel11.setText("Senhas de uso unico:");

    l_senha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_senha1.setText("jLabel12");

    l_senha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_senha2.setText("jLabel12");

    l_senha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_senha3.setText("jLabel12");

    l_senha4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_senha4.setText("jLabel12");

    l_senha5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_senha5.setText("jLabel12");

    l_senha6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_senha6.setText("jLabel12");

    l_senha7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_senha7.setText("jLabel12");

    l_senha8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_senha8.setText("jLabel12");

    l_senha9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_senha9.setText("jLabel12");

    l_senha10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_senha10.setText("jLabel12");

    b_voltarConsulta.setText("Voltar ao menu principal");
    b_voltarConsulta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_voltarConsultaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout p_consultaLayout = new javax.swing.GroupLayout(p_consulta);
    p_consulta.setLayout(p_consultaLayout);
    p_consultaLayout.setHorizontalGroup(
      p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_consultaLayout.createSequentialGroup()
        .addGroup(p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(p_consultaLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(p_consultaLayout.createSequentialGroup()
                .addComponent(l_senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_senha6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jLabel11)
              .addGroup(p_consultaLayout.createSequentialGroup()
                .addComponent(l_senha2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_senha7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(p_consultaLayout.createSequentialGroup()
                .addComponent(l_senha3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_senha8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(p_consultaLayout.createSequentialGroup()
                .addComponent(l_senha4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_senha9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(p_consultaLayout.createSequentialGroup()
                .addComponent(l_senha5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_senha10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(p_consultaLayout.createSequentialGroup()
            .addGap(138, 138, 138)
            .addComponent(b_voltarConsulta)))
        .addContainerGap(25, Short.MAX_VALUE))
    );
    p_consultaLayout.setVerticalGroup(
      p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_consultaLayout.createSequentialGroup()
        .addComponent(jLabel11)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(l_senha1)
          .addComponent(l_senha6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(l_senha2)
          .addComponent(l_senha7))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(l_senha3)
          .addComponent(l_senha8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(l_senha4)
          .addComponent(l_senha9))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(l_senha5)
          .addComponent(l_senha10))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
        .addComponent(b_voltarConsulta)
        .addContainerGap())
    );

    p_sair.setBorder(javax.swing.BorderFactory.createTitledBorder("Saida do sistema: "));

    l_msgSaida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    l_msgSaida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_msgSaida.setText("Pressione o botao Sair para confirmar.");

    b_Sair.setText("Sair");
    b_Sair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_SairActionPerformed(evt);
      }
    });

    b_voltar.setText("Voltar");
    b_voltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_voltarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout p_sairLayout = new javax.swing.GroupLayout(p_sair);
    p_sair.setLayout(p_sairLayout);
    p_sairLayout.setHorizontalGroup(
      p_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_sairLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(p_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(b_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(b_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(l_msgSaida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        .addContainerGap())
    );
    p_sairLayout.setVerticalGroup(
      p_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_sairLayout.createSequentialGroup()
        .addComponent(l_msgSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(b_voltar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(b_Sair)
        .addContainerGap())
    );

    p_alterar.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar: "));

    jLabel13.setText("Senha Pessoal:");

    jLabel14.setText("Confirmacao:");

    jLabel15.setText("Total de senhas de uso unico");

    cb_quantidadeSenhasCartaoAltera.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

    b_alterar.setText("Alterar");
    b_alterar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_alterarActionPerformed(evt);
      }
    });

    b_alteraVoltar.setText("Voltar");
    b_alteraVoltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_alteraVoltarActionPerformed(evt);
      }
    });

    pf_alteraSenhaPessoal.setEditable(false);

    pf_alteraSenhaPessoalConfirma.setEditable(false);

    b_alteraSenhaPessoal.setText("Abrir");
    b_alteraSenhaPessoal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_alteraSenhaPessoalActionPerformed(evt);
      }
    });

    b_alteraSenhaPessoalConfirma.setText("Abrir");
    b_alteraSenhaPessoalConfirma.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_alteraSenhaPessoalConfirmaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout p_alterarLayout = new javax.swing.GroupLayout(p_alterar);
    p_alterar.setLayout(p_alterarLayout);
    p_alterarLayout.setHorizontalGroup(
      p_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_alterarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(p_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(p_alterarLayout.createSequentialGroup()
            .addComponent(b_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
            .addComponent(b_alteraVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(p_alterarLayout.createSequentialGroup()
            .addComponent(jLabel15)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cb_quantidadeSenhasCartaoAltera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(p_alterarLayout.createSequentialGroup()
            .addGroup(p_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_alterarLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pf_alteraSenhaPessoalConfirma))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_alterarLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_alteraSenhaPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(p_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(b_alteraSenhaPessoalConfirma)
              .addComponent(b_alteraSenhaPessoal))))
        .addContainerGap())
    );
    p_alterarLayout.setVerticalGroup(
      p_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_alterarLayout.createSequentialGroup()
        .addGroup(p_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel13)
          .addComponent(pf_alteraSenhaPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(b_alteraSenhaPessoal))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel14)
          .addComponent(pf_alteraSenhaPessoalConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(b_alteraSenhaPessoalConfirma))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel15)
          .addComponent(cb_quantidadeSenhasCartaoAltera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
        .addGroup(p_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(b_alterar)
          .addComponent(b_alteraVoltar))
        .addContainerGap())
    );

    p_cadastra.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastra: "));
    p_cadastra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    p_cadastra.setPreferredSize(new java.awt.Dimension(463, 195));

    jLabel2.setText("Nome do usuario:");

    jLabel4.setText("Login:");

    jLabel6.setText("Grupo:");

    cb_grupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Usuario" }));
    cb_grupo.setSelectedItem(-1);

    jLabel7.setText("Senha Pessoal:");

    jLabel8.setText("Confirmacao:");

    jLabel9.setText("Total de senhas de uso unico");

    cb_quantidadeSenhasCartao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
    cb_quantidadeSenhasCartao.setSelectedItem(-1);

    b_cadastrar.setText("Cadastrar");
    b_cadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_cadastrarActionPerformed(evt);
      }
    });

    b_voltarCadastra.setText("Voltar");
    b_voltarCadastra.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_voltarCadastraActionPerformed(evt);
      }
    });

    b_limpar.setText("Limpar");
    b_limpar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_limparActionPerformed(evt);
      }
    });

    pf_CadastraSenhaPessoal.setEditable(false);

    pf_CadastraSenhaPessoalConfirma.setEditable(false);

    b_CadastraSenhaPessoal.setText("Abrir");
    b_CadastraSenhaPessoal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_CadastraSenhaPessoalActionPerformed(evt);
      }
    });

    b_CadastraSenhaPessoalConfirma.setText("Abrir");
    b_CadastraSenhaPessoalConfirma.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_CadastraSenhaPessoalConfirmaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout p_cadastraLayout = new javax.swing.GroupLayout(p_cadastra);
    p_cadastra.setLayout(p_cadastraLayout);
    p_cadastraLayout.setHorizontalGroup(
      p_cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_cadastraLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(p_cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(p_cadastraLayout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tf_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
          .addGroup(p_cadastraLayout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tf_login, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(45, 45, 45)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
            .addComponent(cb_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(p_cadastraLayout.createSequentialGroup()
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cb_quantidadeSenhasCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(p_cadastraLayout.createSequentialGroup()
            .addComponent(b_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
            .addComponent(b_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(73, 73, 73)
            .addComponent(b_voltarCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(p_cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_cadastraLayout.createSequentialGroup()
              .addComponent(jLabel7)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(pf_CadastraSenhaPessoal)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(b_CadastraSenhaPessoal))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_cadastraLayout.createSequentialGroup()
              .addComponent(jLabel8)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(pf_CadastraSenhaPessoalConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(b_CadastraSenhaPessoalConfirma))))
        .addContainerGap())
    );
    p_cadastraLayout.setVerticalGroup(
      p_cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_cadastraLayout.createSequentialGroup()
        .addGroup(p_cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(tf_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6)
          .addComponent(cb_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(pf_CadastraSenhaPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(b_CadastraSenhaPessoal))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8)
          .addComponent(pf_CadastraSenhaPessoalConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(b_CadastraSenhaPessoalConfirma))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(p_cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9)
          .addComponent(cb_quantidadeSenhasCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
        .addGroup(p_cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(b_cadastrar)
          .addComponent(b_voltarCadastra)
          .addComponent(b_limpar)))
    );

    p_cabecalho.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLabel1.setText("Login:");

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLabel3.setText("Grupo:");

    l_grupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_grupo.setText("bla");

    l_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_login.setText("bla");

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLabel5.setText("Descricao:");

    ta_descricao.setColumns(20);
    ta_descricao.setEditable(false);
    ta_descricao.setLineWrap(true);
    ta_descricao.setRows(5);
    jScrollPane1.setViewportView(ta_descricao);

    javax.swing.GroupLayout p_cabecalhoLayout = new javax.swing.GroupLayout(p_cabecalho);
    p_cabecalho.setLayout(p_cabecalhoLayout);
    p_cabecalhoLayout.setHorizontalGroup(
      p_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_cabecalhoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(p_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
          .addGroup(p_cabecalhoLayout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(l_login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(l_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel5))
        .addContainerGap())
    );
    p_cabecalhoLayout.setVerticalGroup(
      p_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_cabecalhoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(p_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(l_login)
          .addComponent(l_grupo)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    p_totalSUV.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

    jLabel10.setText("Total de senhas de unica vez do usuario:");

    l_totalSUV.setFont(new java.awt.Font("Tahoma", 1, 14));
    l_totalSUV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    l_totalSUV.setText("jLabel11");

    javax.swing.GroupLayout p_totalSUVLayout = new javax.swing.GroupLayout(p_totalSUV);
    p_totalSUV.setLayout(p_totalSUVLayout);
    p_totalSUVLayout.setHorizontalGroup(
      p_totalSUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_totalSUVLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel10)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(l_totalSUV, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        .addContainerGap())
    );
    p_totalSUVLayout.setVerticalGroup(
      p_totalSUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_totalSUVLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(p_totalSUVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel10)
          .addComponent(l_totalSUV))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    p_menuPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu principal: "));
    p_menuPrincipal.setPreferredSize(new java.awt.Dimension(460, 195));

    b_cadastrarUsuario.setText("Cadastrar Novo Usuario");
    b_cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_cadastrarUsuarioActionPerformed(evt);
      }
    });

    b_AlterarUsuario.setText("Alterar Atributos");
    b_AlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_AlterarUsuarioActionPerformed(evt);
      }
    });

    b_consultarUsusario.setText("Consultar Atributos");
    b_consultarUsusario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_consultarUsusarioActionPerformed(evt);
      }
    });

    b_sairSistema.setText("Sair do Sistema");
    b_sairSistema.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        b_sairSistemaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout p_menuPrincipalLayout = new javax.swing.GroupLayout(p_menuPrincipal);
    p_menuPrincipal.setLayout(p_menuPrincipalLayout);
    p_menuPrincipalLayout.setHorizontalGroup(
      p_menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_menuPrincipalLayout.createSequentialGroup()
        .addGap(95, 95, 95)
        .addGroup(p_menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(b_sairSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(b_consultarUsusario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(b_AlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(b_cadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(103, Short.MAX_VALUE))
    );
    p_menuPrincipalLayout.setVerticalGroup(
      p_menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(p_menuPrincipalLayout.createSequentialGroup()
        .addComponent(b_cadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(b_AlterarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(b_consultarUsusario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(b_sairSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    p_telaPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    p_telaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    p_telaPrincipal.setPreferredSize(new java.awt.Dimension(500, 500));

    javax.swing.GroupLayout p_telaPrincipalLayout = new javax.swing.GroupLayout(p_telaPrincipal);
    p_telaPrincipal.setLayout(p_telaPrincipalLayout);
    p_telaPrincipalLayout.setHorizontalGroup(
      p_telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 454, Short.MAX_VALUE)
    );
    p_telaPrincipalLayout.setVerticalGroup(
      p_telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 411, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(p_telaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(p_telaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-474)/2, (screenSize.height-453)/2, 474, 453);
  }// </editor-fold>//GEN-END:initComponents

  private boolean ehAlfanumerico(String s) {
    Character c = null;
    for(int i = 0; i < s.length(); i++) {
      c = s.charAt(i);
      if(!Character.isLetterOrDigit(c) && !Character.isSpaceChar(c)) {
        return false;
      }
    }

    return true;
  }

    private void b_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cadastrarActionPerformed

      controlador.salvaRegistro(6002, controlador.getUsuarioCorrente().getLogin());

      String nome = tf_nome.getText();
      String login = tf_login.getText();

      if(nome.length() > 50 || nome.length() == 0) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Campo do nome: nao pode ser vazio e nao pode ter mais do que 50 caracteres.");
        return;
      }

      if(!ehAlfanumerico(nome)) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Campo do nome: contem caracteres que nao sao alfanumericos.");
        return;
      }

      if(login.length() > 20 || login.length() == 0) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Campo de login: nao pode ser vazio e nao pode ter mais do que 20 caracteres.");
        return;
      }

      if(controlador.existeUsuario(tf_login.getText())) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Campo de login: usuario ja existe.");
        return;
      }

      if(!ehAlfanumerico(login)) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Campo do login: contem caracteres que nao sao alfanumericos.");
        return;
      }

      char[] senha = pf_CadastraSenhaPessoal.getPassword();
      char[] senhaConfirma = pf_CadastraSenhaPessoalConfirma.getPassword();

      if((senha.length > 6 || senha.length == 0)) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Campo de senha: nao pode ser vazio e nao pode ter mais do que 3 fonemas.");
        return;
      }

      if(senhaConfirma.length > 6 || senhaConfirma.length == 0) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Campo de Confirmacao de senha: nao pode ser vazio e nao pode ter mais do que 3 fonemas.");
        return;
      }

      if(String.valueOf(senha).compareTo(String.valueOf(senhaConfirma)) != 0) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Senhas diferentes.");
        return;
      }

      controlador.cadastraUsuario(nome,
                                  login,
                                  (String) cb_grupo.getSelectedItem(),
                                  String.valueOf(senha),
                                  Integer.parseInt(cb_quantidadeSenhasCartao.getSelectedItem().toString()));

      JOptionPane.showMessageDialog(this.getContentPane(), login + ": cadastrado com sucesso.");

      mostraTelaPrincipal();

      tf_nome.setText("");
      tf_login.setText("");
      pf_CadastraSenhaPessoal.setText("");
      pf_CadastraSenhaPessoalConfirma.setText("");
      cb_grupo.setSelectedIndex(0);
      cb_quantidadeSenhasCartao.setSelectedIndex(0);
    }//GEN-LAST:event_b_cadastrarActionPerformed

    private void b_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limparActionPerformed
      tf_nome.setText("");
      tf_login.setText("");
      pf_CadastraSenhaPessoal.setText("");
      pf_CadastraSenhaPessoalConfirma.setText("");
      cb_grupo.setSelectedIndex(0);
      cb_quantidadeSenhasCartao.setSelectedIndex(0);
    }//GEN-LAST:event_b_limparActionPerformed

    private void b_cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cadastrarUsuarioActionPerformed
      controlador.salvaRegistro(5002, controlador.getUsuarioCorrente().getLogin());
      mostraTelaCadastra();
    }//GEN-LAST:event_b_cadastrarUsuarioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

      if(controlador.retornaSenhasLivres().isEmpty()) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Para sair, eh necessario ter pelo menos uma senha de uso unico.");
        //return;
      } else {
        controlador.deslogaUsuario();
        System.exit(0);
      }

    }//GEN-LAST:event_formWindowClosing

    private void b_AlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_AlterarUsuarioActionPerformed
      controlador.salvaRegistro(5003, controlador.getUsuarioCorrente().getLogin());
      mostraTelaAltera();
    }//GEN-LAST:event_b_AlterarUsuarioActionPerformed

    private void b_consultarUsusarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_consultarUsusarioActionPerformed
      controlador.salvaRegistro(5004, controlador.getUsuarioCorrente().getLogin());
      mostraTelaConsulta();
    }//GEN-LAST:event_b_consultarUsusarioActionPerformed

    private void b_sairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sairSistemaActionPerformed
      controlador.salvaRegistro(5005, controlador.getUsuarioCorrente().getLogin());
      mostraTelaSaida();
    }//GEN-LAST:event_b_sairSistemaActionPerformed

    private void b_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterarActionPerformed

      controlador.salvaRegistro(7002, controlador.getUsuarioCorrente().getLogin());

      char[] senha = pf_alteraSenhaPessoal.getPassword();
      char[] senhaConfirma = pf_alteraSenhaPessoalConfirma.getPassword();

      if((senha.length > 6 || senha.length == 0)) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Campo de senha: nao pode ser vazio e nao pode ter mais do que 3 fonemas.");
        return;
      }

      if(senhaConfirma.length > 6 || senhaConfirma.length == 0) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Campo de Confirmacao de senha: nao pode ser vazio e nao pode ter mais do que 3 fonemas.");
        return;
      }

      if(String.valueOf(senha).compareTo(String.valueOf(senhaConfirma)) != 0) {
        JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Senhas diferentes.");
        return;
      }

      String qtdSenhasCartao = (String) cb_quantidadeSenhasCartaoAltera.getSelectedItem();
      controlador.alteraUsuario(String.valueOf(senha), Integer.valueOf(qtdSenhasCartao));

      mostraTelaPrincipal();

      preencheTotalSUV(String.valueOf(controlador.retornaSenhasLivres().size()));

      JOptionPane.showMessageDialog(this.getContentPane(), "Atributos alterados.");

      pf_alteraSenhaPessoal.setText("");
      pf_alteraSenhaPessoalConfirma.setText("");
      cb_quantidadeSenhasCartaoAltera.setSelectedIndex(0);
    }//GEN-LAST:event_b_alterarActionPerformed

    private void b_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SairActionPerformed

      controlador.salvaRegistro(9002, controlador.getUsuarioCorrente().getLogin());

      if(controlador.retornaSenhasLivres().isEmpty()) {
       JOptionPane.showMessageDialog(this.getContentPane(),
                                      "Para sair, eh necessario ter pelo menos uma senha de uso unico.\n"
                                      + "Pressione o botao Voltar de Sair para o Menu Principal.");
      } else {

        controlador.deslogaUsuario();
      }

    }//GEN-LAST:event_b_SairActionPerformed

    private void b_CadastraSenhaPessoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CadastraSenhaPessoalActionPerformed

      new cTelaFonemas(this, pf_CadastraSenhaPessoal).setVisible(true);

    }//GEN-LAST:event_b_CadastraSenhaPessoalActionPerformed

    private void b_CadastraSenhaPessoalConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CadastraSenhaPessoalConfirmaActionPerformed

      new cTelaFonemas(this, pf_CadastraSenhaPessoalConfirma).setVisible(true);

    }//GEN-LAST:event_b_CadastraSenhaPessoalConfirmaActionPerformed

    private void b_alteraSenhaPessoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alteraSenhaPessoalActionPerformed

      new cTelaFonemas(this, pf_alteraSenhaPessoal).setVisible(true);

    }//GEN-LAST:event_b_alteraSenhaPessoalActionPerformed

    private void b_alteraSenhaPessoalConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alteraSenhaPessoalConfirmaActionPerformed

      new cTelaFonemas(this, pf_alteraSenhaPessoalConfirma).setVisible(true);

    }//GEN-LAST:event_b_alteraSenhaPessoalConfirmaActionPerformed

    private void b_voltarCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_voltarCadastraActionPerformed
      controlador.salvaRegistro(6003, controlador.getUsuarioCorrente().getLogin());
      mostraTelaPrincipal();
    }//GEN-LAST:event_b_voltarCadastraActionPerformed

    private void b_alteraVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alteraVoltarActionPerformed
      controlador.salvaRegistro(7003, controlador.getUsuarioCorrente().getLogin());
      mostraTelaPrincipal();
    }//GEN-LAST:event_b_alteraVoltarActionPerformed

    private void b_voltarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_voltarConsultaActionPerformed
      controlador.salvaRegistro(8002, controlador.getUsuarioCorrente().getLogin());
      mostraTelaPrincipal();
    }//GEN-LAST:event_b_voltarConsultaActionPerformed

    private void b_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_voltarActionPerformed
      controlador.salvaRegistro(9003, controlador.getUsuarioCorrente().getLogin());
      mostraTelaPrincipal();
    }//GEN-LAST:event_b_voltarActionPerformed
  /**
   * @param args the command line arguments
   */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new cTelaPrincipal().setVisible(true);
//            }
//        });
//    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton b_AlterarUsuario;
  private javax.swing.JButton b_CadastraSenhaPessoal;
  private javax.swing.JButton b_CadastraSenhaPessoalConfirma;
  private javax.swing.JButton b_Sair;
  private javax.swing.JButton b_alteraSenhaPessoal;
  private javax.swing.JButton b_alteraSenhaPessoalConfirma;
  private javax.swing.JButton b_alteraVoltar;
  private javax.swing.JButton b_alterar;
  private javax.swing.JButton b_cadastrar;
  private javax.swing.JButton b_cadastrarUsuario;
  private javax.swing.JButton b_consultarUsusario;
  private javax.swing.JButton b_limpar;
  private javax.swing.JButton b_sairSistema;
  private javax.swing.JButton b_voltar;
  private javax.swing.JButton b_voltarCadastra;
  private javax.swing.JButton b_voltarConsulta;
  private javax.swing.JComboBox cb_grupo;
  private javax.swing.JComboBox cb_quantidadeSenhasCartao;
  private javax.swing.JComboBox cb_quantidadeSenhasCartaoAltera;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel l_grupo;
  private javax.swing.JLabel l_login;
  private javax.swing.JLabel l_msgSaida;
  private javax.swing.JLabel l_senha1;
  private javax.swing.JLabel l_senha10;
  private javax.swing.JLabel l_senha2;
  private javax.swing.JLabel l_senha3;
  private javax.swing.JLabel l_senha4;
  private javax.swing.JLabel l_senha5;
  private javax.swing.JLabel l_senha6;
  private javax.swing.JLabel l_senha7;
  private javax.swing.JLabel l_senha8;
  private javax.swing.JLabel l_senha9;
  private javax.swing.JLabel l_totalSUV;
  private javax.swing.JLabel l_totalUsuarios;
  private javax.swing.JLabel label;
  private javax.swing.JPanel p_alterar;
  private javax.swing.JPanel p_cabecalho;
  private javax.swing.JPanel p_cadastra;
  private javax.swing.JPanel p_consulta;
  private javax.swing.JPanel p_menuPrincipal;
  private javax.swing.JPanel p_sair;
  private javax.swing.JPanel p_telaPrincipal;
  private javax.swing.JPanel p_totalSUV;
  private javax.swing.JPanel p_totalUsuarios;
  private javax.swing.JPasswordField pf_CadastraSenhaPessoal;
  private javax.swing.JPasswordField pf_CadastraSenhaPessoalConfirma;
  private javax.swing.JPasswordField pf_alteraSenhaPessoal;
  private javax.swing.JPasswordField pf_alteraSenhaPessoalConfirma;
  private javax.swing.JTextArea ta_descricao;
  private javax.swing.JTextField tf_login;
  private javax.swing.JTextField tf_nome;
  // End of variables declaration//GEN-END:variables
}
